### ISSUE TITLE
카드의 기본적인 구조를 만든다. 카드와 덱을 구현.

### ISSUE THREAD

**Issue by 110V** [TeamODD/Ratocalypse#9]

**Comment by qazxsw1240** [comment]
덱의 기능이 무덤 기능과 겹치는 부분이 많아 카드를 저장하고 꺼내는 카드 컬렉션 클래스를 구현하고 덱과 무덤이 그 컬렉션 클래스를 각각 상속받아 덱과 무덤마다 필요한 기능을 따로 구현해야 할 것 같습니다.
